#MSDS 6306 Assignment 5
Kevin Dickens
September 30th, 2017

### Question 1
*Data Munging (30 points): Utilize yob2016.txt for this question. This file is a series of popular children's names born in the year 2016 in the United States. It consists of three columns with a first name, a gender, and the amount of children given that name. However, the data is raw and will need cleaning to make it tidy and usable.*

##### **1a. First, import the .txt file into R so you can process it. Keep in mind this is not a CSV file. You might have to open the file to see what you're dealing with. Assign the resulting data frame to an object, df, that consists of three columns with human-readable column names for each.**

```r
df<-read.table("yob2016.txt",sep=";",header=FALSE, col.names=c("Name","Sex","Instances"))
```

##### **1b. Display the summary and structure of df.**

```r
summary(df)
str(df)
```

##### **1c. Your client tells you that there is a problem with the raw file. One name was entered twice and misspelled. The client cannot remember which name it is; there are thousands he saw! But he did mention he accidentally put three y's at the end of the name. Write an R command to figure out which name it is and display it.**

```r
df[grep("yyy$",df$Name),]
```

##### **1d. Upon finding the misspelled name, please remove this particular observation, as the client says it's redundant. Save the remaining dataset as an object: y2016.**

```r
y2016<-df[-grep("yyy$",df$Name),]
```

### Question 2
*Data Merging (30 points): Utilize yob2015.txt for this question. This file is similar to yob2016, but contains names, gender, and total children given that name for the year 2015.*

##### **2a. Like 1a, please import the .txt file into R. Look at the file before you do. You might have to change some options to import it properly. Again, please give the dataframe human-readable column names. Assign the dataframe to y2015.**

```r
y2015<-read.table("yob2015.txt",sep=",",header=FALSE, col.names=c("Name","Sex","Instances"))
```

##### **2b. Display the last ten rows in the dataframe. Describe something you find interesting about these 10 rows.**

```r
tail(y2015, 10)
```
It's interesting that all of these names have 5 observations each.

##### **2c. The client is expecting a girl! Omit boys and give the top 10 most popular girl's names. Assign this to object girl.**

```r
girl<-y2015[-grep("M",df$Sex),]
girl<-girl[1:10,]
```

##### **2d. Write these top 10 girl Names and their Totals to a CSV file called itsagirl.csv. Do not include row labels. Leave out columns other than Name and Total.**

```r
write.csv(girl, "itsagirl.csv")
```
### *4.  Upload to GitHub (10 points): Push at minimum your RMarkdown for this homework assignment and a Readme file with Codebook to one of your GitHub repositories (you might place this in a Homework repo like last week). It does not have to be too detailed. The Codebook should contain a short definition of each object you create. You are welcome and encouraged to add other files-just make sure you have a description and directions that are helpful for the grader.*

```r
browseURL("https://github.com/JanuaryRaven/SMU_MSDS_Homework/tree/master/Unit5")
```