---
title: "Unit11 Lecture Assignment"
author: "Kevin Dickens"
date: "November 6, 2017"
output: html_document
---

### Include code for entering data

```{r, echo=TRUE}
library(tseries)

#Guggenheim S&P 500 Equal Weight 
RSPdata<-get.hist.quote('rsp',quote="Close")
```

### calculating log returns

```{r, echo=TRUE}
RSPret<-log(lag(RSPdata))-log(RSPdata)
RSPvol<-sd(RSPret)*sqrt(250)*100
```

### calculating volatility measure

```{r, echo=TRUE}
Vol<-function(d, logrets){
  var=0
  lam=0
  varlist<-c()
  for (r in logrets){
    lam=lam*(1-1/d)+1
    var=(1-1/lam)*var+(1/lam)*r^2
    varlist<-c(varlist, var)
  }
  sqrt(varlist)
}
```

### calculating volatility for the entire series using three different decay factors.

```{r, echo=TRUE}
volest<-Vol(10, RSPret)
volest2<-Vol(30, RSPret)
volest3<-Vol(100, RSPret)
```

### Code for plot (and the plot) with volatility estimates for various values of d overlaid.

```{r, echo=TRUE}
plot(volest, type="l")
lines(volest2, type="l", col="red")
lines(volest3, type="l", col="blue")
```